// ============================================================================
// @okdoc-ai/plugin-sdk — Iframe SDK Global Type Declarations (AUTO-GENERATED)
//
// DO NOT EDIT THIS FILE MANUALLY.
// Generated by scripts/build-iframe-sdk.mjs from src/iframe-sdk-types.ts.
// To update, edit that file and run:  npm run build:all
//
// Usage in iframe plugin projects:
//   Copy this file into your project's src/ directory, OR reference it
//   in tsconfig.json → "include": ["path/to/okdoc-iframe-sdk-global.d.ts"]
// ============================================================================
interface OkDocJsonSchemaProperty {
    type?: string | string[];
    description?: string;
    enum?: unknown[];
    const?: unknown;
    default?: unknown;
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    format?: string;
    minimum?: number;
    maximum?: number;
    items?: OkDocJsonSchemaProperty | OkDocJsonSchemaProperty[];
    minItems?: number;
    maxItems?: number;
    properties?: Record<string, OkDocJsonSchemaProperty>;
    required?: string[];
    additionalProperties?: boolean | OkDocJsonSchemaProperty;
    oneOf?: OkDocJsonSchemaProperty[];
    anyOf?: OkDocJsonSchemaProperty[];
    allOf?: OkDocJsonSchemaProperty[];
    not?: OkDocJsonSchemaProperty;
    [key: string]: unknown;
}
interface OkDocToolInputSchema {
    type: 'object';
    properties?: Record<string, OkDocJsonSchemaProperty>;
    required?: string[];
}
interface OkDocAnnotations {
    audience?: ('user' | 'assistant')[];
    priority?: number;
    lastModified?: string;
}
interface OkDocToolAnnotations {
    title?: string;
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    idempotentHint?: boolean;
    openWorldHint?: boolean;
}
interface OkDocContentBlock {
    type: 'text' | 'image' | 'audio' | 'resource' | 'resource_link';
    text?: string;
    data?: string;
    mimeType?: string;
    uri?: string;
    name?: string;
    description?: string;
    resource?: {
        uri: string;
        mimeType?: string;
        text?: string;
        blob?: string;
    };
    annotations?: OkDocAnnotations;
}
interface OkDocToolResult {
    content: OkDocContentBlock[];
    structuredContent?: Record<string, unknown>;
    isError?: boolean;
}
interface OkDocToolConfig {
    description: string;
    inputSchema?: OkDocToolInputSchema;
    annotations?: OkDocToolAnnotations;
    handler: (args: Record<string, unknown>) => Promise<OkDocToolResult>;
}
interface OkDocPluginAuthor {
    /** Author or company name */
    name: string;
    /** Contact email */
    email?: string;
    /** Website or profile URL */
    url?: string;
}
interface OkDocInitOptions {
    /** Unique plugin identifier */
    id: string;
    /** Display name shown in the Plugin Store */
    name: string;
    /** Short description */
    description?: string;
    /** Semver version of the plugin */
    version: string;
    /** Ionicon name for the store card */
    icon?: string;
    /** MCP namespace prefix for all tools */
    namespace: string;
    /** Display mode: foreground (visible UI) or background (hidden) */
    mode?: 'foreground' | 'background';
    /** Plugin author / company info (required: name + email or url) */
    author: OkDocPluginAuthor;
    /** Allowed origins for the host handshake. If omitted, any origin is accepted. */
    allowedOrigins?: string[];
}
interface OkDocIframeSDK {
    /** Initialize the plugin with its manifest. Must be called before registerTool(). */
    init(options: OkDocInitOptions): void;
    /** Register a tool that the host app (AI) can call. */
    registerTool(name: string, config: OkDocToolConfig): void;
    /**
     * Send a notification message to the AI.
     * Only works after the host has connected via handshake.
     */
    notify(message: string): void;
    /** Clean up the SDK: remove event listeners, close port, clear state. */
    destroy(): void;
    /** Current iframe protocol version */
    readonly version: number;
    /** MCP protocol version this SDK targets */
    readonly mcpProtocolVersion: string;
}

declare var OkDoc: OkDocIframeSDK;
