/**
 * scripts/stamp-version.mjs — Reads version from package.json and writes src/version.ts.
 *
 * Called automatically as the first step of `npm run build:all`.
 * This keeps package.json as the SINGLE source of truth for the SDK version.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

const content = `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit manually.
// Source of truth: package.json "version" field.
export const OKDOC_SDK_VERSION = '${pkg.version}';
`;

writeFileSync(resolve(root, 'src/version.ts'), content, 'utf8');
console.log(`✅ Stamped version ${pkg.version} → src/version.ts`);
